In [2]:
import scanpy as sc

In [2]:
adata=sc.read("/dfs3b/ruic20_lab/junw42/HCA_ON/data/9_Brain_h5ad/GSE167494_more/GSE167494_more_hvg_10000_epoch_none_seurat_rs_1_sb_scvi_trg.h5ad")

In [3]:
import pandas as pd

In [4]:
obs=pd.read_csv("/dfs3b/ruic20_lab/junw42/HCA_ON/data/9_Brain_h5ad/sadick_2022_LEN_metadata_matrix.csv",header=0,index_col=0)

In [5]:
obs["bc"]=[obs.loc[x,"sample"]+"_"+obs.loc[x,"barcode"] for x in obs.index]

In [6]:
obs.head()

,sample,barcode,sex,disease_id,age,YOD,MMSE,PMI,RIN,cell_type_label,astrocyte_subtype,oligodendrocyte_subtype,bc
AAACCCAAGGCAGGGA-1.D1_DMEM,D1_DMEM,AAACCCAAGGCAGGGA-1,M,NS,90,2011,NaN,12.0,8.3,Astro_B,5.0,NaN,D1_DMEM_AAACCCAAGGCAGGGA-1
AAGCGAGAGTCTGGAG-1.D1_DMEM,D1_DMEM,AAGCGAGAGTCTGGAG-1,M,NS,90,2011,NaN,12.0,8.3,Astro_B,5.0,NaN,D1_DMEM_AAGCGAGAGTCTGGAG-1
AAGCGTTAGTCAGAGC-1.D1_DMEM,D1_DMEM,AAGCGTTAGTCAGAGC-1,M,NS,90,2011,NaN,12.0,8.3,Astro_A,2.0,NaN,D1_DMEM_AAGCGTTAGTCAGAGC-1
AAGGTAAAGTGCACTT-1.D1_DMEM,D1_DMEM,AAGGTAAAGTGCACTT-1,M,NS,90,2011,NaN,12.0,8.3,Astro_B,2.0,NaN,D1_DMEM_AAGGTAAAGTGCACTT-1
AAGTTCGAGGCTTAGG-1.D1_DMEM,D1_DMEM,AAGTTCGAGGCTTAGG-1,M,NS,90,2011,NaN,12.0,8.3,Astro_A,6.0,NaN,D1_DMEM_AAGTTCGAGGCTTAGG-1

In [29]:
obs["cell_type_label"].value_counts()

cell_type_label
Astro_A      34733
Oligo        23840
Astro_B       6607
Neuro_A       4747
Neuro_B       2936
Micro         2716
OPC           2427
Endo-like     2241
Name: count, dtype: int64

In [12]:
idx=adata.obs.index.intersection(obs["bc"])

In [13]:
adata1=adata[idx]

In [19]:
#obs=obs.set_index("bc")
adata1.obs["celltype"]=obs.loc[idx,"cell_type_label"].astype("str")

In [23]:
adata1.obs[["nCount_RNA","leiden", "celltype"]].groupby(["leiden", "celltype"]).size().unstack(fill_value=0)

/tmp/ipykernel_3782775/4948170.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  adata1.obs[["nCount_RNA","leiden", "celltype"]].groupby(["leiden", "celltype"]).size().unstack(fill_value=0)

celltype  Astro_A  Astro_B  Endo-like  Micro  Neuro_A  Neuro_B   OPC  Oligo
leiden
0               0        2          6      0        1       21     0  13796
1           15517      109          4      0        0       20     0      0
2           11162      154          5      1        0       12     0      0
3               0        0          0      0        0        4     0   7438
4               0        0          0      0     3765        2     0      0
5             323     3894          1      2        0        0     0      1
6            2161     1927          6      0        0        1     0      0
7            3931      157          2      0        0       11     0      0
8               7        7          0   2426        0        0     0      2
9              11        0          0      0        4        2     0      0
10              0        2          0      0        0        1  2240      1
11              0        0          0      0        0        0     0   1614
12              0        0          0      0        0     1170     1      0
13              0        0          0      0        3      648     3      0
14              0        0       1021      0        0        0     0      1
15              4       31          1      1      265       96     1      1
16              0        0          0      0      272        0     0      0
17              0        2        645      1        0        0     0      3
18            593        3          0      0        0        2     0      0
19              0        0          0      0        0      309     0      0
20              0        9        319      3        0        0     0      0
21              0        0          0      0       95        0     0      0
22              0        0          0      0        0      406     0      0
23              0        0          0      0        2       72     0      1
24              0        0          0      0       61        0     0      0
25             21        1          0      0        0        0     0     26
26              0        3          0      0        0        1     0    122
27              0        0          0      0       39        2    13      0
28              0       63          0      0        0        1     0      0
29              2       11          0      0        0        0     0      0
31              0        0          0      0        7        0     0      0
32              0        0          0     46        0        0     0      1

In [7]:
adata2=sc.read("/dfs3b/ruic20_lab/junw42/HCA_ON/data/9_Brain_h5ad/GSE167494_more/GSE167494_more.h5ad")

In [8]:
obs=obs.set_index("bc")
idx=adata2.obs.index.intersection(obs.index)

In [9]:
adata2=adata2[idx]
adata2.obs["celltype"]=obs.loc[idx,"cell_type_label"].astype("str")

/tmp/ipykernel_3785422/2962023062.py:2: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  adata2.obs["celltype"]=obs.loc[idx,"cell_type_label"].astype("str")

In [10]:
adata2[(adata2.obs["celltype"]=="Oligo")].write("/dfs3b/ruic20_lab/junw42/HCA_ON/data/9_Brain_h5ad/GSE167494_more/author_oligo.h5ad")

/opt/apps/python/3.10.2/lib/python3.10/site-packages/anndata/_core/anndata.py:1138: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

In [11]:
adata2[(adata2.obs["celltype"]=="Astro_A") | (adata2.obs["celltype"]=="Astro_B") ].write("/dfs3b/ruic20_lab/junw42/HCA_ON/data/9_Brain_h5ad/GSE167494_more/author_astro.h5ad")

/opt/apps/python/3.10.2/lib/python3.10/site-packages/anndata/_core/anndata.py:1138: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c